### ISSUE TITLE
stopWork() crashes when attempting to call onTransitionToIdle()

### ISSUE THREAD

**Issue by jameswald** [square/RxIdler#26]
This started happening in 0.10.0 but works fine in 0.9.1:

```
E/AndroidRuntime: FATAL EXCEPTION: RxIoScheduler-2
    Process: com.example.test, PID: 7030
    java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void androidx.test.espresso.IdlingResource$ResourceCallback.onTransitionToIdle()' on a null object reference
        at com.squareup.rx.idler.DelegatingIdlingResourceScheduler.stopWork(DelegatingIdlingResourceScheduler.java:100)
        at com.squareup.rx.idler.DelegatingIdlingResourceScheduler$ScheduledWork.call(DelegatingIdlingResourceScheduler.java:148)
        at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
```

Not yet sure whether this is my fault. Here's how we registering the idler:

```
class ExampleAndroidJUnitRunner : AndroidJUnitRunner() {
    override fun onStart() {
        RxJavaPlugins.getInstance().registerSchedulersHook(RxIdler.hooks())
        IdlingRegistry.getInstance().register(
            RxIdler.wrap(AndroidSchedulers.mainThread(), "Android Main Thread Scheduler")
        )
        super.onStart()
    }
}
```

**Comment by jameswald** [comment]
Probably a dupe of https://github.com/square/RxIdler/issues/20.

**Comment by emartynov** [comment]
So what was your fix?

**Comment by jameswald** [comment]
We moved `super.onStart()` from the end of the `onStart()` function to the beginning of that function.

**Comment by jameswald** [comment]
It turns out this is not what you want to do because all the tests are executed from super.onStart(). 😭
