### ISSUE TITLE
RxIdler does not wait until network request get finished

### ISSUE THREAD

**Issue by Ali-Rezaei** [square/RxIdler#36]
Here is my method which I want to test :

```
@Test
    fun shouldBeAbleToScrollViewAndDisplayRuleDetails() {
        onView(withId(R.id.recyclerView)).perform(RecyclerViewActions
            .actionOnItemAtPosition<MainAdapter.SavingsGoalViewHolder>(5, click()))
        onView(withText(R.string.your_rules)).check(matches(isDisplayed()))
    }
```

I receive following exception :

```
at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1736)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:88)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:51)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:314)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:297)
	at com.sample.android.qapital.TestMainActivity.shouldBeAbleToScrollViewAndDisplayRuleDetails(TestMainActivity.kt:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:388)
	at com.sample.android.qapital.AppTestRunner.onStart(AppTestRunner.kt:18)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
     Got: "AppCompatTextView{id=-1, visibility=VISIBLE, width=0, height=0, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=true, is-selected=false, layout-params=android.widget.LinearLayout$LayoutParams@52b82ea, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, text=Your\nRules, input-type=0, ime-target=false, has-links=false}"

	at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:539)
	at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:103)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:415)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:279)
	at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:265)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

It seems RxIdler does not wait as expected. I have used RxIdler in similar projects and it seems to work.

Here is source code of my project : https://github.com/Ali-Rezaei/SavingGoals-Cache

**Comment by Kisty** [comment]
Looking at your code https://github.com/alirezaeiii/SavingGoals-Cache/blob/b24607538351e88ee5942bca7b41f422a4eb7903/app/src/androidTest/java/com/sample/android/goals/AppTestRunner.kt#L15 I think there's a difference with `RxJavaPlugins#setInitIoSchedulerHander()` and `RxJavaPlugins#setIoSchedulerHander()` (no `...Init...`). I know this because I too have been burned by this. Try that and it might just fix the test. Also, just check you're not using your `ImmediateSchedulerProvider`
